/**
 * 
 */
package de.binfalse.martin.jeopardy.client.x;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import de.binfalse.martin.jeopardy.client.net.ClientSpeaker;



// TODO: Auto-generated Javadoc
/**
 * The Class DialogPanel.
 *
 * @author Martin Scharm
 */
public class DialogPanel
	extends JDialog
{
	
	/** The j button1. */
	private javax.swing.JButton			jButton1;
	
	/** The j label1. */
	private javax.swing.JLabel			jLabel1;
	
	/** The j label2. */
	private javax.swing.JLabel			jLabel2;
	
	/** The j label3. */
	private javax.swing.JLabel			jLabel3;
	
	/** The j text field1. */
	private javax.swing.JTextField	jTextField1;
	
	/** The j text field2. */
	private javax.swing.JTextField	jTextField2;
	
	/** The j text field3. */
	private javax.swing.JTextField	jTextField3;
	
	/** The cs. */
	private ClientSpeaker						cs;
	
	
	/**
	 * Instantiates a new dialog panel.
	 */
	public DialogPanel ()
	{
		init ();
	}
	
	
	/**
	 * Instantiates a new dialog panel.
	 *
	 * @param owner the owner
	 * @param modal the modal
	 */
	public DialogPanel (Frame owner, boolean modal)
	{
		super (owner, modal);
		init ();
	}
	
	
	/**
	 * Gets the speaker.
	 *
	 * @return the speaker
	 */
	public ClientSpeaker getSpeaker ()
	{
		return cs;
	}
	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void init ()
	{
		
		jLabel1 = new javax.swing.JLabel ();
		jLabel2 = new javax.swing.JLabel ();
		jLabel3 = new javax.swing.JLabel ();
		jTextField1 = new javax.swing.JTextField ();
		jTextField2 = new javax.swing.JTextField ();
		jTextField3 = new javax.swing.JTextField ();
		jButton1 = new javax.swing.JButton ();
		
		jLabel1.setText ("Server:");
		
		jLabel2.setText ("Port:");
		
		jLabel3.setText ("Name:");
		
		jTextField1.setText ("192.168.9.88");
		
		jTextField2.setText ("1234");
		
		jTextField3.setText ("YourName");
		
		jButton1.setText ("connect");
		jButton1.addActionListener (new ActionListener ()
		{
			
			@Override
			public void actionPerformed (ActionEvent e)
			{
				String host = jTextField1.getText ();
				String port = jTextField2.getText ();
				int p = -1;
				String name = jTextField3.getText ();
				String error = "";
				if (host.length () < 1)
					error += "> no valid host\n";
				if (port.length () < 1)
					error += "> no valid port\n";
				else
				{
					try
					{
						p = Integer.parseInt (port);
					}
					catch (NumberFormatException ex)
					{
						error += "> cannot parse port\n";
					}
				}
				if (name.length () < 1)
					error += "> no valid name\n";
				
				if (error.length () > 0)
				{
					JOptionPane.showMessageDialog (DialogPanel.this,
						"Following errors occurred:\n" + error, "Errors",
						JOptionPane.ERROR_MESSAGE);
					return;
				}
				
				try
				{
					cs = new ClientSpeaker (host, p, name);
					dispose ();
				}
				catch (IOException ex)
				{
					ex.printStackTrace ();
					JOptionPane.showMessageDialog (DialogPanel.this,
						"Cannot connect to server:\n" + ex.getMessage (),
						"Error connecting", JOptionPane.ERROR_MESSAGE);
				}
			}
			
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout (
			this.getContentPane ());
		this.getContentPane ().setLayout (layout);
		layout.setHorizontalGroup (layout.createParallelGroup (
			javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup (
				layout
					.createSequentialGroup ()
					.addContainerGap ()
					.addGroup (
						layout
							.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup (
								layout
									.createSequentialGroup ()
									.addGroup (
										layout
											.createParallelGroup (
												javax.swing.GroupLayout.Alignment.LEADING)
											.addComponent (jLabel1).addComponent (jLabel2)
											.addComponent (jLabel3))
									.addPreferredGap (
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
									.addGroup (
										layout
											.createParallelGroup (
												javax.swing.GroupLayout.Alignment.LEADING)
											.addComponent (jTextField1).addComponent (jTextField2)
											.addComponent (jTextField3)))
							.addGroup (
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
									.createSequentialGroup ()
									.addPreferredGap (
										javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388,
										Short.MAX_VALUE).addComponent (jButton1)))
					.addContainerGap ()));
		layout.setVerticalGroup (layout.createParallelGroup (
			javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup (
				layout
					.createSequentialGroup ()
					.addContainerGap ()
					.addGroup (
						layout
							.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent (jLabel1)
							.addComponent (jTextField1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup (
						layout
							.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent (jLabel2)
							.addComponent (jTextField2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup (
						layout
							.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE)
							.addComponent (jLabel3)
							.addComponent (jTextField3,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
					.addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup (
						layout.createParallelGroup (
							javax.swing.GroupLayout.Alignment.BASELINE).addComponent (
							jButton1))
					.addContainerGap (javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)));
		pack ();
	}
}
